---
- name: Create Jenkins agent user
  user:
    name: jenkins
    shell: /bin/bash
    create_home: yes

- name: Create Jenkins agent directory
  file:
    path: /home/jenkins/agent
    state: directory
    owner: jenkins
    group: jenkins
    mode: '0755'

- name: Download Jenkins agent JAR
  get_url:
    url: "http://jenkins-dev.homelab.local/jnlpJars/agent.jar"
    dest: "/home/jenkins/agent/agent.jar"
    owner: jenkins
    group: jenkins
    mode: '0644'

- name: Create systemd service file for Jenkins agent
  template:
    src: jenkins-agent.service.j2
    dest: /etc/systemd/system/jenkins-agent.service
  notify: Restart Jenkins Agent

- name: Enable and start Jenkins agent service
  systemd:
    name: jenkins-agent
    enabled: yes
    state: started
    daemon_reload: yes
